version: '3.8'

services:
  # Reverse Proxy
  nginx-reverse-proxy:
    build: ./nginx-reverse-proxy
    ports:
      - "80:80"
    depends_on:
      - authentication-service
      - user-service
      - workout-service
      - nutrition-service
      - recommendation-service
    networks:
      - fitness-network

  # Authentication Service
  authentication-service:
    build: ./authentication-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:authdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - JWT_SECRET=mySecretKey
      - JWT_EXPIRATION=86400000
    networks:
      - fitness-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # User Service
  user-service:
    build: ./user-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:userdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - AUTHENTICATION_SERVICE_URL=http://authentication-service:8081
      - JWT_SECRET=mySecretKey
    depends_on:
      - authentication-service
    networks:
      - fitness-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8082/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Workout Service
  workout-service:
    build: ./workout-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:workoutdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - AUTHENTICATION_SERVICE_URL=http://authentication-service:8081
      - USER_SERVICE_URL=http://user-service:8082
      - JWT_SECRET=mySecretKey
    depends_on:
      - authentication-service
      - user-service
    networks:
      - fitness-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8083/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nutrition Service
  nutrition-service:
    build: ./nutrition-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:nutritiondb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - AUTHENTICATION_SERVICE_URL=http://authentication-service:8081
      - USER_SERVICE_URL=http://user-service:8082
      - JWT_SECRET=mySecretKey
    depends_on:
      - authentication-service
      - user-service
    networks:
      - fitness-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8084/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Recommendation Service
  recommendation-service:
    build: ./recommendation-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AUTHENTICATION_SERVICE_URL=http://authentication-service:8081
      - USER_SERVICE_URL=http://user-service:8082
      - WORKOUT_SERVICE_URL=http://workout-service:8083
      - NUTRITION_SERVICE_URL=http://nutrition-service:8084
      - AI_GEMINI_API_KEY=${AI_GEMINI_API_KEY:-test-key}
      - AI_GEMINI_API_URL=${AI_GEMINI_API_URL:-https://test-url}
      - JWT_SECRET=mySecretKey
    depends_on:
      - authentication-service
      - user-service
      - workout-service
      - nutrition-service
    networks:
      - fitness-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8085/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  fitness-network:
    driver: bridge
