# =============================================================================
# FITNESS APPLICATION - STAGING ENVIRONMENT (YAML)
# =============================================================================

spring:
  profiles:
    active: staging
  
  # Staging Database (PostgreSQL - similar to prod but separate instance)
  datasource:
    url: ${STAGING_DATABASE_URL:jdbc:postgresql://localhost:5432/fitness_app_staging}
    driver-class-name: org.postgresql.Driver
    username: ${STAGING_DATABASE_USERNAME:postgres}
    password: ${STAGING_DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
  
  # H2 Console disabled in staging
  h2:
    console:
      enabled: false
  
  # JPA Configuration for staging
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # More lenient than prod for testing
    show-sql: true # Enabled for debugging
    format-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# Staging Server Configuration
server:
  port: ${SERVER_PORT:8080}
  error:
    include-stacktrace: on_param
    include-message: always

# Staging Logging (balanced verbosity)
logging:
  level:
    com.fitness_application: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    root: INFO
  file:
    name: logs/fitness-app-staging.log
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 10

# Staging JWT settings
jwt:
  expiration: ${JWT_EXPIRATION:7200000} # 2 hours for staging

# Staging CORS (moderately permissive)
cors:
  allowed:
    origins: ${STAGING_CORS_ORIGINS:https://staging.fitness-app.com,http://localhost:3000}

app:
  cors:
    allowed-origins: ${STAGING_CORS_ORIGINS:https://staging.fitness-app.com,http://localhost:3000}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

# Staging Swagger Configuration (enabled for testing)
springdoc:
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
  api-docs:
    enabled: true

# Staging Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: when_authorized
    env:
      show-values: when_authorized
