# =============================================================================
# FITNESS APPLICATION - DEVELOPMENT ENVIRONMENT (YAML)
# =============================================================================

spring:
  profiles:
    active: dev
  
  # Development Database (H2 in-memory)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # H2 Console enabled for development
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  
  # JPA Configuration for development
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true

# Development Server Configuration
server:
  port: 8080
  error:
    include-stacktrace: always
    include-message: always

# Development Logging (more verbose)
logging:
  level:
    com.fitness_application: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
  file:
    name: logs/fitness-app-dev.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5

# Development JWT settings (shorter expiration for testing)
jwt:
  expiration: 3600000 # 1 hour for development

# Development CORS (more permissive)
cors:
  allowed:
    origins: http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000

app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
    allowed-headers: "*"
    allow-credentials: true

# Development Swagger Configuration
springdoc:
  swagger-ui:
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  api-docs:
    resolve-schema-properties: true

# Development Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
